name: "Detect chess"
on:
#  issues:
#    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Triggering issue number'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
jobs:
  what_branch:
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -xe
        echo "TEST_MODE=no" >> $GITHUB_ENV
    - if: ${{ github.event_name == 'issue' }} && startsWith(github.event.issue.title, 'chess|') && ! contains(github.event.issue.labels.*.name, 'test')
      run: |
        set -xe
        echo "TEST_MODE=no" >> $GITHUB_ENV
        echo "GAME_BRANCH=master" >> $GITHUB_ENV
    - if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        set -xe        
        ISSUE_BODY=$(echo "$(gh issue view $INPUT_ISSUE_NUMBER --json body)" | xargv)
        PR_COUNT=$(gh pr list --head "$ISSUE_BODY" --json number | jq ". | length")
        
        if [[ $PR_COUNT == 0 ]]; then
          echo "TEST_MODE=no" >> $GITHUB_ENV
          echo "GAME_BRANCH=master" >> $GITHUB_ENV
        else
          echo "TEST_MODE=yes" >> $GITHUB_ENV
          echo "GAME_BRANCH=$ISSUE_BODY" >> $GITHUB_ENV
        fi
    - name: trigger the game
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
        owner: timburgan
        repo: timburgan
        ref: ${{ env.GAME_BRANCH }}
        workflow_id: chess.yml
        inputs: '{ "game_branch": "${{ env.GAME_BRANCH }}", "test_mode": "${{ env.TEST_MODE }}"}'
